<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridCuewEUDOperations.aspx.cs" Inherits="EmployeeMgmt.GridCuewEUDOperations" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView runat="server" AutoGenerateColumns="False" ID="gvstudents" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" Height="269px"  Width="723px" OnRowCancelingEdit="gvstudents_RowCancelingEdit" OnRowDeleted="gvstudents_RowDeleted" OnRowDeleting="gvstudents_RowDeleting" OnRowEditing="gvstudents_RowEditing" OnRowUpdating="gvstudents_RowUpdating" OnSelectedIndexChanged="gvstudents_SelectedIndexChanged">
                <Columns        >
                    <asp:TemplateField  HeaderText="sid" >
                        <ItemTemplate>
                            <asp:Label Text='<%# Eval("sid") %>' ID="lblsid" runat="server" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField  HeaderText="class" >
                        <ItemTemplate>
                            <asp:Label Text='<%# Eval("class") %>' ID="lblclass" runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate >
                            <asp:TextBox runat="server" ID ="txtclass"  Text='<%# Eval("class") %>' />
                        </EditItemTemplate>  
                    </asp:TemplateField>
                    <asp:TemplateField  HeaderText="Fname" >
                        <ItemTemplate>
                            <asp:Label Text='<%# Eval("fname") %>' ID="lblfname" runat="server" />
                        </ItemTemplate>
                        <EditItemTemplate >
                            <asp:TextBox runat="server" ID ="txtfname"  Text='<%# Eval("fname") %>' />
                        </EditItemTemplate>  
                    </asp:TemplateField>
                      <asp:TemplateField  HeaderText="Lname" >
                        <ItemTemplate>
                            <asp:Label Text='<%# Eval("lname") %>' ID="lbllname" runat="server" />
                        </ItemTemplate>
                         <EditItemTemplate >
                            <asp:TextBox runat="server" ID ="txtlname"  Text='<%# Eval("lname") %>' />
                        </EditItemTemplate>  
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
